"""Add organization, building and activity tables

Revision ID: a202680d1617
Revises: 
Create Date: 2025-10-04 01:29:17.841698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a202680d1617'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('parent_sid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_sid'], ['activity.activity.sid'], ),
    sa.PrimaryKeyConstraint('sid'),
    schema='activity',
    comment='activity module schema'
    )
    op.create_index(op.f('ix_activity_activity_name'), 'activity', ['name'], unique=False, schema='activity')
    op.create_table('building',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    schema='building',
    comment='building module schema'
    )
    op.create_index(op.f('ix_building_building_address'), 'building', ['address'], unique=False, schema='building')
    op.create_table('organization',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    schema='organization',
    comment='organization module schema'
    )
    op.create_index(op.f('ix_organization_organization_name'), 'organization', ['name'], unique=False, schema='organization')
    op.create_table('organization_activity',
    sa.Column('organization_sid', sa.Uuid(), nullable=False),
    sa.Column('activity_sid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_sid'], ['activity.activity.sid'], ),
    sa.ForeignKeyConstraint(['organization_sid'], ['organization.organization.sid'], ),
    sa.PrimaryKeyConstraint('organization_sid', 'activity_sid'),
    schema='organization',
    comment='organization module schema'
    )
    op.create_index(op.f('ix_organization_organization_activity_activity_sid'), 'organization_activity', ['activity_sid'], unique=False, schema='organization')
    op.create_index(op.f('ix_organization_organization_activity_organization_sid'), 'organization_activity', ['organization_sid'], unique=False, schema='organization')
    op.create_table('organization_address',
    sa.Column('organization_sid', sa.Uuid(), nullable=False),
    sa.Column('building_sid', sa.Uuid(), nullable=False),
    sa.Column('office', sa.String(length=25), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_sid'], ['building.building.sid'], ),
    sa.ForeignKeyConstraint(['organization_sid'], ['organization.organization.sid'], ),
    sa.PrimaryKeyConstraint('organization_sid', 'building_sid'),
    schema='organization',
    comment='organization module schema'
    )
    op.create_table('phone_number',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('organization_sid', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_sid'], ['organization.organization.sid'], ),
    sa.PrimaryKeyConstraint('sid'),
    schema='organization',
    comment='organization module schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_number', schema='organization')
    op.drop_table('organization_address', schema='organization')
    op.drop_index(op.f('ix_organization_organization_activity_organization_sid'), table_name='organization_activity', schema='organization')
    op.drop_index(op.f('ix_organization_organization_activity_activity_sid'), table_name='organization_activity', schema='organization')
    op.drop_table('organization_activity', schema='organization')
    op.drop_index(op.f('ix_organization_organization_name'), table_name='organization', schema='organization')
    op.drop_table('organization', schema='organization')
    op.drop_index(op.f('ix_building_building_address'), table_name='building', schema='building')
    op.drop_table('building', schema='building')
    op.drop_index(op.f('ix_activity_activity_name'), table_name='activity', schema='activity')
    op.drop_table('activity', schema='activity')
    # ### end Alembic commands ###
